export default interface Rajjus {
  Anuradha: 'csipő'
  Ardra: 'nyak'
  Ashlesha: 'láb'
  Ashwini: 'láb'
  Bharani: 'csípő'
  Chitra: 'fej'
  Dhanishta: 'fej'
  Hasta: 'nyak'
  Jyeshta: 'láb'
  Krithika: 'köldök'
  Magha: 'láb'
  Mrigashirsha: 'fej'
  Moola: 'láb'
  Punarvasu: 'köldök'
  'Purva Bhadrapada': 'köldök'
  'Purva Ashadha': 'csípő'
  Pushya: 'csípő'
  Revati: 'láb'
  Rohini: 'nyak'
  Shatabhisha: 'nyak'
  Shravana: 'nyak'
  Swati: 'nyak'
  'Uttara Ashadha': 'köldök'
  'Uttara Bhadrapada': 'csípő'
  'Uttara Phalguni': 'köldök'
  Vishaka: 'köldök'
}
